sudo: false
language: node_js
notifications:
  email: true
node_js:
  - '5.1.0'
before_install:
  - npm i -g npm@^3.5.0
before_script:
  - npm i -g gulp
script:
  - gulp build
  - travis_wait 30 node dist/index.js
branches:
  only:
    - master
